### ISSUE TITLE
Vehicle Actor type available when module is not active (D&D 5e)

### ISSUE THREAD

**Issue by Radagast9** [grandseiken/foundryvtt-vehicles-and-mechanisms#5]
In a D&D 5e world on a computer with the Vehicles and Mechanisms module installed, when creating a new actor the dropdown menu for actor type includes 'vehicle' even if the module is not activated for that world.

In addition, this may also lead to conflict with the [Loot Sheet NPC 5e module by jopeek](https://github.com/jopeek/fvtt-loot-sheet-npc-5e) which is also supposed to add a new actor type.
With Loot Sheet NPC 5e active and Vehicles and Mechanisms inactive, the NPC loot sheet does not appear on the new actor type dropdown in a 5e world.
![image](https://user-images.githubusercontent.com/73142378/96517177-71b2a880-1236-11eb-8f3a-c41120a27566.png)

**Comment by grandseiken** [comment]
Hi, I think there is some confusion here. Vehicles and Mechanisms does not add any actor type. I believe the vehicle actor type is part of DND5e itself and doesn't have anything to do with the Vehicles and Mechanisms module. In addition, a module that is inactive can't cause conflicts or affect the world really in any way since it won't even be loaded.

**Comment by Radagast9** [comment]
My mistake! Thank you for the quick response and clarification.
